version: '3'
services:
  web:
    image: nginx:latest
    environment:
      - ROOT=basename $PWD
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./build:/app
  php:
    image: php:fpm
    volumes:
      - ./build:/app